#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:12:30:00

module load R

echo hostname
#cd /crucible/mc48o9p/hqin2/mactower-network-failure-simulation-master/ms02GINPPI
cd /oasis/scratch/hongqin/temp_project/Slim-network-aging-bio386-fall-2015
pwd

for p in 1.0 0.98 0.95 0.9 0.88 0.85 0.82 0.8 0.78 
do
   for LOne in 0.001 0.0015 0.002 0.0025 0.003
   do
      echo "$p $LOne"
      R --vanilla --slave -f 20151101-net-sim-ginppi.R --args $LOne 0.0002 5 $p 1000
   done
done
